### ISSUE TITLE
Query not working

### ISSUE THREAD

**Issue by jakesylvestre** [skpy/Namecheap-REST-PHP#3]
Hey so I'm attempting this

``` php
<?php
include_once( 'namecheap.php' );
$domain = 'jakesyl.com';
$TLD = substr($domain, -3);//all my domains have 3 letter tlds
$SLD = substr($domain, 0, strlen($domain)-3);

$nc_api = array( 'api_user' => 'jakesyl',
        'api_key' => 'apikeyishere',
        'api_ip' => 'appip'
    );


$sandbox = 'true'; // use the Namecheap sandbox to test
$nc = new Namecheap( $nc_api, $sandbox );

$data = array (
    "SLD" => $SLD,
    "TLD" => $TLD,
    "HostName" => $domain,
    "RecordType" => "A",
    "Address" => "ipishere",
    "TTL" => 180
    );

if ( ! $nc->dnsSetHosts( $domain, $data ) ) {

    print_r( $nc->Error );//TODO if theres an error email us

}

?>

```

So I'm not sure whats wrong here, I have another file in the same directory registering the domains thats working fine and I copied and pasted lines 1-14, this code throws no errors

**Comment by skpy** [comment]
Showing no errors would seem to indicate that the process was successful.

To test this, you can try several things.  First, to see the full response from Namecheap, change the latter portion of your script to this:

``` php
$nc->dnsSetHosts( $domain, $data )
print_r( $nc->Raw );
exit;
```

That will show you everything that Namecheap sends back, allowing you to examine whether it was a success or failure.

Alternately, you could put a simple `else` clause to confirm that Namecheap is responding with a success:

``` php
if ( ! $nc->dnsSetHosts( $domain, $data ) ) {
    print_r( $nc->Error );//TODO if theres an error email us
} else {
    print "Success!";
    // or: print_r( $nc->Raw);
}
```

**Comment by jakesylvestre** [comment]
It's odd because when I check the namecheap dashboard nothing is different
